trigger:
  - master
  - develop
stages:
  - stage: build
    displayName: Build
    jobs:
      - job: default
        displayName: Default
        pool: 
          name: LabAgents
        steps:
          - task: gittools.gitversion.gitversion-task.GitVersion@4
            displayName: GitVersion 
            inputs: 
              preferBundledVersion: false
          - task: DotNetCoreCLI@2
            inputs:
              command: build
              versioningScheme: byBuildNumber
  - stage: test
    displayName: Test
    jobs:
      - job: unit
        displayName: Unit
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: test
  - stage: publish
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish
    jobs:
      - job: package
        displayName: Package
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: pack
              configuration: Release
              versioningScheme: byEnvVar
              versionEnvVar: GitVersion.NuGetVersion
          - task: NuGetCommand@2
            inputs:
              command: push
              nuGetFeedType: external
              publishFeedCredentials: NuGet
              versioningScheme: byBuildNumber