trigger:
  - master
  - develop
  - release/*
  - feature/*
  - bugfix/*
  - hotfix/*
  - refs/tags/*

steps:
  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: install GitVersion.CommandLine -Version 4.0.0 -OutputDirectory $(Build.BinariesDirectory)/tools -ExcludeVersion
      
  - script: mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output buildserver /nofetch

  - task: DotNetCoreCLI@2
    inputs:
      command: build
      versioningScheme: byBuildNumber

  - task: DotNetCoreCLI@2
    inputs:
      command: test

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      configuration: Release
      versioningScheme: byEnvVar
      versionEnvVar: GitVersion.NuGetVersion

  - task: NuGetCommand@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: NuGet
      versioningScheme: byBuildNumber
