trigger:
  - master
  - develop
  - release/*
  - feature/*
  - bugfix/*
  - hotfix/*
  - refs/tags/*

variables:
  suffix: -CI.$(Build.BuildId)

steps:
  - bash: |
      if [ $(Build.SourceBranch) ~= refs/tags/* ]; then \
        echo "##vso[task.setvariable variable=suffix]"; \
      fi

  - bash: dotnet build -c Release --version-suffix $(suffix)
  - bash: dotnet test --no-build
  - bash: dotnet pack -c Release --no-build --version-suffix $(suffix)
    
  - task: DotNetCoreCLI@2
    inputs:
      command: push
      nuGetFeedType: internal
      configuration: Release
      publishVstsFeed: 9251c6a1-c000-47ee-8e03-02d656a9418f

  - task: NuGetCommand@2
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: NuGet