trigger:
  - master
  - develop
  - release/*
  - feature/*
  - bugfix/*
  - hotfix/*
  - refs/tags/*

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    inputs:
      command: test

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      command: pack
      configuration: Release
      versioningScheme: byEnvVar
      versionEnvVar: Build.SourceBranchName

  - task: NuGetCommand@2
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: NuGet
      versioningScheme: byEnvVar
      versionEnvVar: Build.SourceBranchName
