trigger:
  - master
  - develop
  - release/*
  - feature/*
  - bugfix/*
  - hotfix/*
  - refs/tags/*

variables:
  suffix: -CI.$(Build.BuildId)

steps:
  - bash: |
      if [ $(Build.SourceBranch) ~= refs/tags/* ]; then \
        echo "##vso[task.setvariable variable=suffix]"; \
      fi

  - bash: dotnet build -c Release --version-suffix $(suffix)
  - bash: dotnet test -c Release --no-build
  - bash: dotnet pack -c Release --no-build --version-suffix $(suffix) --output $(Build.ArtifactStagingDirectory)
    
  - task: DotNetCoreCLI@2
    inputs:
      command: push
      nuGetFeedType: internal
      configuration: Release
      publishVstsFeed: 3c2d2c8b-6319-47d4-bc73-f36d7ab7a9f8/9a760305-cfa3-4d6b-9e6c-9fb664931e1d

  - task: NuGetCommand@2
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: NuGet