trigger:
  - master
  - develop
  - release/*
  - feature/*
  - bugfix/*
  - hotfix/*
  - refs/tags/*

pool:
  name: Default

steps:
  - task: GitVersion@4
    displayName: GitVersion 
    inputs:
      updateAssemblyInfo: true

  - task: DotNetCoreCLI@2
    inputs:
      command: build
      versioningScheme: byBuildNumber

  - task: DotNetCoreCLI@2
    inputs:
      command: test

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      configuration: Release
      versioningScheme: byEnvVar
      versionEnvVar: GitVersion.NuGetVersion

  - task: NuGetCommand@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: NuGet
      versioningScheme: byBuildNumber
      