variables:
  MAJOR: 0
  MINOR: 1
trigger:
  - master
  - develop
stages:
  - stage: build
    displayName: Build
    jobs:
      - job: default
        displayName: Default
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: build
          - bash: export VERSION=$(cat .release);
  - stage: test
    displayName: Test
    jobs:
      - job: unit
        displayName: Unit
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: test
  - stage: publish
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish
    jobs:
      - job: package
        displayName: Package
        variables:
          PATCH: $[counter(format('{0}.{1}', variables['MAJOR'], variables['MINOR']), 0)]
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: pack
              configuration: Release
              versioningScheme: byPrereleaseNumber
              majorVersion: $(MAJOR)
              minorVersion: $(MINOR)
              patchVersion: $(PATCH)
          - task: NuGetCommand@2
            inputs:
              command: push
              nuGetFeedType: external
              publishFeedCredentials: NuGet
              versioningScheme: byPrereleaseNumber
              majorVersion: $(MAJOR)
              minorVersion: $(MINOR)
              patchVersion: $(PATCH)