version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      - rm -rf /usr/share/dotnet && mkdir -p /usr/share/dotnet
      - yum install -y libunwind dotnet-sdk-2.1
  build:
    commands:
      - dotnet --info
      - dotnet test -c Release
      - dotnet msbuild tools/package.proj -p:Configuration=Release -p:Optimize=true
artifacts:
  discard-paths: yes
  files:
    - "Core.template.yml"
    - "Core.config.json"
    - "Utilities.template.yml"
    - "Resources.template.yml"
    - "Dns.template.yml"
    - "Dns.config.json"