version: 0.2
env:
  variables:
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"

phases:
  install:
    runtime-versions:
      dotnet: 3.1

  build:
    commands:
      - dotnet --info
      - dotnet test -c Release --logger trx
      - dotnet msbuild tools/package.proj -p:Configuration=Release -p:DeploymentBucket=$ARTIFACT_STORE -p:DeploymentBucketPrefix=$ARTIFACT_PREFIX/templates
      - ./tools/create-networking-config.sh > Networking.config.json

artifacts:
  discard-paths: yes
  files:
    - "Core.template.yml"
    - "Core.config.json"
    - "Utilities.template.yml"
    - "Resources.template.yml"
    - "Dns.template.yml"
    - "Dns.config.json"
    - "Gateway.template.yml"
    - "Networking.config.json"

reports:
  test-results:
    files:
      - "**/TestResults/*.trx"
    discard-paths: yes
    file-format: VisualStudioTrx
