version: 0.2
env:
  variables:
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
    DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY: "false"
    DOTNET_NOLOGO: "true"

phases:
  install:
    runtime-versions:
      docker: 19

    commands:
      - dotnet-install.sh --channel 6.0
      - dotnet-install.sh --jsonfile global.json
      - dotnet --info

  build:
    commands:
      - dotnet test -c Release --logger trx
      - dotnet msbuild tools/package.proj -p:Configuration=Release -p:DeploymentBucket=$ARTIFACT_STORE -p:DeploymentBucketPrefix=$ARTIFACT_PREFIX
      - ./tools/create-networking-config.sh > Networking.config.json

artifacts:
  discard-paths: yes
  files:
    - "Core.template.yml"
    - "Core.config.json"
    - "Utilities.template.yml"
    - "Layers.template.yml"
    - "Layers.config.json"
    - "Dns.template.yml"
    - "Dns.config.json"
    - "Gateway.template.yml"
    - "Networking.config.json"
    - "package-manifest.json"

reports:
  test-results:
    files:
      - "**/TestResults/*.trx"
    discard-paths: yes
    file-format: VisualStudioTrx
