version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      - yum install -y libunwind
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 3.0.100 --install-dir /usr/share/dotnet
      - export PATH="$PATH:/usr/share/dotnet"
  build:
    commands:
      - dotnet --info
      - dotnet restore
      - dotnet msbuild tools/package.proj -p:Configuration=Release
      - dotnet test -c Release --no-build
      
artifacts:
  discard-paths: yes
  files:
    - "Core.template.yml"
    - "Core.config.json"
    - "Utilities.template.yml"
    - "Resources.template.yml"
    - "Dns.template.yml"
    - "Dns.config.json"