version: 0.2
env:
  variables:
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"

  exported-variables:
    - DEV_PEERING_ID
    - PROD_PEERING_ID

phases:
  install:
    runtime-versions:
      dotnet: 3.1

  build:
    commands:
      - dotnet --info
      - dotnet restore
      - dotnet test -c Release
      - dotnet msbuild tools/package.proj -p:Configuration=Release -p:DeploymentBucket=$ARTIFACT_STORE
      - . ./tools/create-networking-config.sh

artifacts:
  discard-paths: yes
  files:
    - "Core.template.yml"
    - "Core.config.json"
    - "Utilities.template.yml"
    - "Resources.template.yml"
    - "Dns.template.yml"
    - "Dns.config.json"
