version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      # - rm -rf /usr/share/dotnet && mkdir -p /usr/share/dotnet
      # - yum install -y libunwind
      # - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 2.1.508 --install-dir /usr/share/dotnet
      - export PATH="$PATH:/usr/share/dotnet"
  build:
    commands:
      - dotnet --info
      - dotnet test -c Release
      - dotnet msbuild tools/package.proj -p:Configuration=Release -p:Optimize=true
artifacts:
  discard-paths: yes
  files:
    - "Core.template.yml"
    - "Core.config.json"
    - "Utilities.template.yml"
    - "Resources.template.yml"
    - "Dns.template.yml"
    - "Dns.config.json"