version: 0.2
env:
  variables:
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"

phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      - yum install -y libunwind
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 3.0.100 --install-dir /usr/share/dotnet
      - export PATH="$PATH:/usr/share/dotnet"

  build:
    commands:
      - dotnet --info
      - dotnet test -c Release
      - dotnet msbuild tools/package.proj -p:Configuration=Release

      # Get networking configuration
      - devPeeringConnectionId=$(aws cloudformation list-exports --query Exports[?Name==\`cfn-core:DevPeeringConnectionId\`].Value --output text)
      - prodPeeringConnectionId=$(aws cloudformation list-exports --query Exports[?Name==\`cfn-core:ProdPeeringConnectionId\`].Value --output text)
      - config={}
      - config=$(echo $config | jq ".DevPeeringConnectionId=\"$devPeeringConnectionId\"") 
      - config=$(echo $config | jq ".ProdPeeringConnectionId=\"$prodPeeringConnectionId\"") 
      - echo $config > Networking.config.json

artifacts:
  discard-paths: yes
  files:
    - "Core.template.yml"
    - "Core.config.json"
    - "Utilities.template.yml"
    - "Resources.template.yml"
    - "Dns.template.yml"
    - "Dns.config.json"
    - "Networking.config.json"