version: 0.2
env:
  variables:
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"

phases:
  install:
    runtime-versions:
      dotnet: 3.1

  pre_build:
    commands:
      - dotnet --info

  build:
    commands:
      - dotnet test -c Release
      - dotnet msbuild tools/package.proj -p:Configuration=Release
      - ./tools/create-networking-config.sh > Networking.config.json

artifacts:
  discard-paths: yes
  files:
    - "Core.template.yml"
    - "Core.config.json"
    - "Utilities.template.yml"
    - "Resources.template.yml"
    - "Dns.template.yml"
    - "Dns.config.json"
    - "Networking.config.json"
    - "Metadata.template.yml"