Parameters:
  GithubToken:
    Type: String
    NoEcho: true
    Description: OAuth token for the Github organization.  Needs read/write access to repos and repo hooks

  GithubOwner:
    Type: String
    Description: Owner of the github repository to track

  GithubRepo:
    Type: String
    Description: Name of the github repository to track

  GithubBranch:
    Type: String
    Description: Name of the github branch to track

Resources:
  ArtifactStore:
    Type: AWS::S3::Bucket

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build
      ServiceRole: !ImportValue cfn-utilities:BuilderRoleArn
      EncryptionKey: !ImportValue cfn-utilities:ArtifactKeyArn
      Environment:
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ARTIFACT_STORE
            Value: !Ref ArtifactStore
        Type: LINUX_CONTAINER
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
  
  Webhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GithubToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: "refs/heads/{Branch}"
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AWS::StackName}-pipeline 
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStore
        EncryptionKey: 
          Id: !ImportValue cfn-utilities:ArtifactKeyArn
          Type: KMS
      RoleArn: !ImportValue cfn-utilities:MasterRoleArn
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Provider: GitHub
                Owner: ThirdParty
                Version: 1
              OutputArtifacts:
                - Name: sourceCode
              Configuration:
                Owner: !Ref GithubOwner
                Repo: !Ref GithubRepo
                Branch: !Ref GithubBranch
                OAuthToken: !Ref GithubToken
                PollForSourceChanges: false
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Provider: CodeBuild
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: sourceCode
              OutputArtifacts:
                - Name: buildResults
              Configuration:
                ProjectName: !Ref BuildProject
        - Name: Deploy
          Actions:
            - Name: Utilities
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: cfn-utilities
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Utilities.template.yml
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                Capabilities: CAPABILITY_NAMED_IAM
            - Name: Resources
              RunOrder: 2
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: cfn-resources
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Resources.template.yml
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                Capabilities: CAPABILITY_IAM
            - Name: DNS
              RunOrder: 3
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: cfn-dns
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Dns.template.yml
                TemplateConfiguration: buildResults::Dns.config.json
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                Capabilities: CAPABILITY_IAM
            - Name: Core
              RunOrder: 4
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: cfn-core
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Core.template.yml
                TemplateConfiguration: buildResults::Core.config.json
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
        - Name: Dev
          Actions:
            - Name: Utilities
              RoleArn: !ImportValue cfn-utilities:MasterRoleArn
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: cfn-utilities
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Utilities.template.yml
                RoleArn: "{{resolve:ssm:DevAgentRoleArn}}"
                ParameterOverrides: !Sub |
                  \{ "MasterAccountId": "${!ImportValue cfn-utilities:MasterRoleArn}" \}
                Capabilities: CAPABILITY_NAMED_IAM
