Description: CICD pipeline for cfn
Parameters:
  GithubToken:
    Type: String
    NoEcho: true
    Description: OAuth token for the Github organization.  Needs read/write access to repos and repo hooks

  GithubOwner:
    Type: String
    Description: Owner of the github repository to track

  GithubRepo:
    Type: String
    Description: Name of the github repository to track

  GithubBranch:
    Type: String
    Description: Name of the github branch to track

Resources:
  ArtifactStore:
    Type: AWS::S3::Bucket

  ArtifactStorePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactStore
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow 
            Action: s3:*Object
            Resource:
              - !Sub arn:aws:s3:::${ArtifactStore}
              - !Sub arn:aws:s3:::${ArtifactStore}/*
            Principal:
              AWS:
                - !Ref AWS::AccountId
                - !ImportValue cfn-metadata:DevAgentRoleArn
                - !ImportValue cfn-metadata:ProdAgentRoleArn

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build
      ServiceRole: !ImportValue cfn-utilities:BuilderRoleArn
      EncryptionKey: !ImportValue cfn-utilities:ArtifactKeyArn
      Environment:
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        ComputeType: BUILD_GENERAL1_SMALL 
        EnvironmentVariables:
          - Name: ARTIFACT_STORE
            Value: !Ref ArtifactStore
        Type: LINUX_CONTAINER
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
  
  Webhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GithubToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: "refs/heads/{Branch}"
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AWS::StackName}-pipeline 
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStore
        EncryptionKey: 
          Id: !ImportValue cfn-utilities:ArtifactKeyArn
          Type: KMS
      RoleArn: !ImportValue cfn-utilities:MasterRoleArn
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Provider: GitHub
                Owner: ThirdParty
                Version: 1
              OutputArtifacts:
                - Name: sourceCode
              Configuration:
                Owner: !Ref GithubOwner
                Repo: !Ref GithubRepo
                Branch: !Ref GithubBranch
                OAuthToken: !Ref GithubToken
                PollForSourceChanges: false
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Provider: CodeBuild
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: sourceCode
              OutputArtifacts:
                - Name: buildResults
              Configuration:
                ProjectName: !Ref BuildProject
        - Name: Metadata
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: cfn-metadata
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Metadata.template.yml
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                ParameterOverrides: !Sub
                - |
                  {
                    "DevAccountId": "${DevAccountId}",
                    "ProdAccountId": "${ProdAccountId}"
                  }
                - DevAccountId: !ImportValue cfn-metadata:DevAccountId
                  ProdAccountId: !ImportValue cfn-metadata:ProdAccountId
                Capabilities: CAPABILITY_IAM
        - Name: Utilities
          Actions:
            - Name: Shared
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: cfn-utilities
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Utilities.template.yml
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                Capabilities: CAPABILITY_NAMED_IAM
            - Name: Dev
              RunOrder: 2
              RoleArn: !ImportValue cfn-metadata:DevAgentRoleArn
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              OutputArtifacts:
                - Name: devUtilityExports
              Configuration:
                StackName: cfn-utilities
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Utilities.template.yml
                RoleArn: !ImportValue cfn-metadata:DevAgentRoleArn
                ParameterOverrides: !Sub |
                  { 
                    "MasterAccountId": "${AWS::AccountId}", 
                    "NetworkCidr": "10.2.0.0/16",
                    "PeeringConnectionId": { "Fn::GetParam": [ "buildResults", "Networking.config.json", "DevPeeringConnectionId" ] }
                  }
                Capabilities: CAPABILITY_NAMED_IAM
                OutputFileName: utility-output.json
            - Name: Prod
              RunOrder: 3
              RoleArn: !ImportValue cfn-metadata:ProdAgentRoleArn
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              OutputArtifacts:
                - Name: prodUtilityExports
              Configuration:
                StackName: cfn-utilities
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Utilities.template.yml
                RoleArn: !ImportValue cfn-metadata:ProdAgentRoleArn
                ParameterOverrides: !Sub |
                  { 
                    "MasterAccountId": "${AWS::AccountId}", 
                    "NetworkCidr": "10.3.0.0/16",
                    "PeeringConnectionId": { "Fn::GetParam": [ "buildResults", "Networking.config.json", "ProdPeeringConnectionId" ] }
                  }
                Capabilities: CAPABILITY_NAMED_IAM
                OutputFileName: utility-output.json
        - Name: Features
          Actions:
            - Name: Resources
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: cfn-resources
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Resources.template.yml
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                Capabilities: CAPABILITY_IAM
            - Name: DNS
              RunOrder: 2
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: cfn-dns
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Dns.template.yml
                TemplateConfiguration: buildResults::Dns.config.json
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                Capabilities: CAPABILITY_IAM
            - Name: Core
              RunOrder: 3
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
                - Name: devUtilityExports
                - Name: prodUtilityExports
              Configuration:
                StackName: cfn-core
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::Core.template.yml
                TemplateConfiguration: buildResults::Core.config.json
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                ParameterOverrides: |
                  {
                    "DevVpcId": { "Fn::GetParam": [ "devUtilityExports", "utility-output.json", "VpcId" ] },
                    "ProdVpcId": { "Fn::GetParam": [ "prodUtilityExports", "utility-output.json", "VpcId" ] },
                    "DevLoadBalancerDnsName": { "Fn::GetParam": [ "devUtilityExports", "utility-output.json", "LoadBalancerDnsName" ] },
                    "ProdLoadBalancerDnsName": { "Fn::GetParam": [ "prodUtilityExports", "utility-output.json", "LoadBalancerDnsName" ] }
                  }
            