Resources:
  ConfigServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: config.amazonaws.com
      Description: Service-linked role for AWS Config.

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    DependsOn: ConfigServiceLinkedRole
    Properties:
      Name: default
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/config.amazonaws.com/AWSServiceRoleForConfig

  ConfigBucket:
    Type: AWS::S3::Bucket

  ConfigBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 
              - s3:GetBucketAcl
              - s3:ListBucket
            Resource: !Sub arn:aws:s3:::${ConfigBucket}
            Principal:
              Service: config.amazonaws.com
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${ConfigBucket}/*
            Principal:
              Service: config.amazonaws.com

  ConfigTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AWS Config Notification Topic

  ConfigSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ConfigTopic
      Protocol: email
      Endpoint: talen.fisher@cythral.com

  ConfigDeliveryPolicy:
    Type: AWS::Config::DeliveryChannel
    Properties:
      S3BucketName: !Ref ConfigBucket
      SnsTopicARN: !Ref ConfigTopic